server:
  port: 8011


#  spring.application.name=spring-cloud-eureka
#
#  server.port=8000
#  eureka.client.register-with-eureka=false
#  eureka.client.fetch-registry=false
#
#  eureka.client.serviceUrl.defaultZone=http://localhost:${server.port}/eureka/
spring:
  application:
    name: spring-cloud-eureka
eureka:
  client:
    register-with-eureka: false # the default is true
    fetch-registry: false # This client gets the registration information on the eureka server registry, the default is true
    #注册中心路径，如果有多个eureka server，在这里需要配置其他eureka server的地址，
    #用","进行区分，如"http://address:8888/eureka,http://address:8887/eureka"
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/


